version: '3.9'

services:
  postgres:
    build: .
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: de-zoomcamp
    ports:
      - "5432:5432" # Map container port to host port
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data

volumes:
  postgres_data:
